apiVersion: v1
kind: Secret
metadata:
  name: dataimport-azure-functions-secret
  namespace: edgraph
data:
  StorageAccount: RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0FjY291bnROYW1lPWVnYWtzY29vbGRldnNjdXM7QWNjb3VudEtleT1JTktTd2ludDJQZGQwTXNYdWtmWEpGSUtlc0xOaVRoUUNJVkk0U3lMNm9JR0NnZTFxN3FodHhYRVdDcHRJUW1XUnpFY2VCemphTGxpK0FTdDAyb3BOQT09O0VuZHBvaW50U3VmZml4PWNvcmUud2luZG93cy5uZXQ=
  queueName: ZGF0YWltcG9ydC10cmFuc2Zvcm1sb2FkLXF1ZXVl
  SqlServerConnectionString: c2VydmVyPWVnLW1zc3FsLXNlcnZlci0wMS1kZXYtc2N1cy5kYXRhYmFzZS53aW5kb3dzLm5ldD1FZEZpX3swfTtVc2VyIElkPWVnc3FsYWRtaW47UGFzc3dvcmQ9ZCU5eThEJHBRZEJ2VkFDcWQjUTUzIUROeTZ6SyUzZkZuUCU7QXBwbGljYXRpb24gTmFtZT1FZEZpLk9kcy5XZWJBcGk7SW50ZWdyYXRlZCBTZWN1cml0eT1mYWxzZTtUcnVzdFNlcnZlckNlcnRpZmljYXRlPVRydWU7