apiVersion: v1
kind: Secret
metadata:
  name: edfi-dataimport-web-azure-functions
  namespace: edgraph
type: Opaque
stringData:
  host.json: |-
    {
      "masterKey": {
        "name": "master",
        "value": "MASTER_KEY",
        "encrypted": false
      },
      "functionKeys": [ ]
    }