apiVersion: v1
kind: Service
metadata:
  name: dataimport-azure-functions-service
  namespace: edgraph
spec:
  selector:
    app: dataimport-azure-functions-pod
  ports:
  - port: 8080
    targetPort: 80
  type: LoadBalancer