apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: dataimport-azure-functions-scale-object
  namespace: edgraph
spec:
  scaleTargetRef:
    name:  dataimport-azure-functions-deployment                            #  <--- K8 object to scale pods
    envSourceContainerName: dataimport-azure-functions-container            #  <--- K8 object to get ENV
  pollingInterval: 5   # Optional. Default: 30 seconds
  cooldownPeriod: 30   # Optional. Default: 300 seconds
  minReplicaCount: 1   # Optional. Default: 0
  maxReplicaCount: 30  # Optional. Default: 100
  triggers:
  - type: azure-queue
    authenticationRef:
      name: dataimport-azure-functions-trig-auth
    metadata:
      queueName: dataimport-transformload-queue
      queueLength: "10"                                                      #  <--- Amount of load a pod can handle
