apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: hello-keda-scaledobject
spec:
  jobTargetRef:
    parallelism: 10
    completions: 1
    #activeDeadlineSeconds: 14400
    #backoffLimit: 6
    ttlSecondsAfterFinished: 100
    template:
      metadata:
        labels:
          app: hello-keda
        name: hello-keda
      spec:
        containers:
          - name: edfi-dataimport-web-azure-functions
            image: ewcontainerscus.azurecr.io/edfi/dataimport-web/azure-functions:bullseye-slim-v1.0.0-azurefunctions.20230131.1
            imagePullPolicy: Always
            env:
              Name:   DOTNET_ENVIRONMENT
              Value:  Development
              Name:   ASPNETCORE_ENVIRONMENT
              Value:  Development
              Name:   AZURE_FUNCTIONS_ENVIRONMENT
              Value:  Development
              Name:   FUNCTIONS_WORKER_RUNTIME
              Value:  dotnet-isolated
              Name:   WEBSITE_HOSTNAME
              Value:  localhost:7071
              Name:   AzureWebJobs.TransformLoad_TimerFunction.Disabled
              Value:  true
              Name:   AzureWebJobsStorage
              Value From:
                Secret Key Ref:
                  Key:   connectionstring
                  Name:  egakscooldevscus-connection-string
              Name:      SQLSERVER_DATASOURCE
              Value:     tcp:eg-mssql-server-01-dev-scus.database.windows.net,1433
              Name:      SQLSERVER_USER
              Value From:
                Secret Key Ref:
                  Key:   username
                  Name:  eg-mssql-server-01-dev-scus-admin-credentials
              Name:      SQLSERVER_PASSWORD
              Value From:
                Secret Key Ref:
                  Key:   password
                  Name:  eg-mssql-server-01-dev-scus-admin-credentials
              Name:      ConnectionStringsStorageConnection
              Value From:
                Secret Key Ref:
                  Key:   connectionstring
                  Name:  egakscooldevscus-connection-string
              Name:      EdGraphStorageConnectionQueueName
              Value:     dataimport-transformload-queue
              Name:      EdGraphTransformLoadTimerTrigger
              Value:     0 */5 * * * *
              Name:      ConnectionStrings__storageConnection
              Value From:
                Secret Key Ref:
                  Key:          connectionstring
                  Name:         egakscooldevscus-connection-string
              Name:             ConnectionStrings__defaultConnection
              Value:            Server=$(SQLSERVER_DATASOURCE);Database=EdFi_{0};User Id=$(SQLSERVER_USER);Password=$(SQLSERVER_PASSWORD);Integrated Security=false;Encrypt=True; Persist Security Info=True;Connection Timeout=3600;Command Timeout=3600;TrustServerCertificate=True;
              Name:             AppSettings__DatabaseEngine
              Value:            SqlServer
              Name:             EdGraph__storageConnection__QueueName
              Value:            dataimport-transformload-queue
              Name:             EdGraph__AzureSQL__ElasticPoolName
              Value:            eg-mssql-elastic-01-dev-scus

  pollingInterval: 30
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  maxReplicaCount: 100
  triggers:
  - type: azure-queue
    authenticationRef:
      name: dataimport-azure-functions-trig-auth
    metadata:
      queueName: dataimport-transformload-queue
      queueLength: "10"                                                      #  <--- Amount of load a pod can handle
