apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: edfi-dataimport-web-azure-functions
  labels:
    app: edfi-dataimport-web-azure-functions
spec:
  jobTargetRef:
    parallelism: 10
    completions: 1
    #activeDeadlineSeconds: 14400
    #backoffLimit: 6
    ttlSecondsAfterFinished: 100
    template:
      metadata:
        labels:
          app: edfi-dataimport-web-azure-functions
        name: edfi-dataimport-web-azure-functions
      spec:
        containers:
          - name: edfi-dataimport-web-azure-functions
            image: ewcontainerscus.azurecr.io/edfi/dataimport-web/azure-functions:bullseye-slim-v1.0.0-azurefunctions.20230131.1
            imagePullPolicy: Always
            env:
              - name: DOTNET_ENVIRONMENT
                value: Development
              - name: ASPNETCORE_ENVIRONMENT
                value: Development
              - name: AZURE_FUNCTIONS_ENVIRONMENT
                value: Development
              - name: FUNCTIONS_WORKER_RUNTIME
                value: dotnet-isolated
              - name: WEBSITE_HOSTNAME
                value: localhost:7071
              - name: AzureWebJobs.TransformLoad_TimerFunction.Disabled
                value: true
              - name: AzureWebJobsStorage
                valueFrom:
                  secretKeyRef:
                    key: connectionstring
                    name: egakscooldevscus-connection-string
              - name: SQLSERVER_DATASOURCE
                value: tcp:eg-mssql-server-01-dev-scus.database.windows.net,1433
              - name: SQLSERVER_USER
                valueFrom:
                  secretKeyRef:
                    key: username
                    name: eg-mssql-server-01-dev-scus-admin-credentials
              - name: SQLSERVER_PASSWORD
                valueFrom:
                  secretKeyRef:
                    key: password
                    name: eg-mssql-server-01-dev-scus-admin-credentials
              - name: ConnectionStringsStorageConnection
                valueFrom:
                  secretKeyRef:
                    key: connectionstring
                    name: egakscooldevscus-connection-string
              - name: EdGraphStorageConnectionQueueName
                value: dataimport-transformload-queue
              - name: EdGraphTransformLoadTimerTrigger
                value: 0 */5 * * * *
              - name: ConnectionStrings__storageConnection
                valueFrom:
                  secretKeyRef:
                    key:  connectionstring
                    name: egakscooldevscus-connection-string
              - name:  ConnectionStrings__defaultConnection
                value: Server=$(SQLSERVER_DATASOURCE);Database=EdFi_{0};User Id=$(SQLSERVER_USER);Password=$(SQLSERVER_PASSWORD);Integrated Security=false;Encrypt=True; Persist Security Info=True;Connection Timeout=3600;Command Timeout=3600;TrustServerCertificate=True;
              - name:  AppSettings__DatabaseEngine
                value: SqlServer
              - name:  EdGraph__storageConnection__QueueName
                value: dataimport-transformload-queue
              - name:  EdGraph__AzureSQL__ElasticPoolName
                value: eg-mssql-elastic-01-dev-scus

  pollingInterval: 30
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  minReplicaCount: 0 # Optional. Default: 0
  maxReplicaCount: 10
  triggers:
  - type: azure-queue
    authenticationRef:
      name: edfi-dataimport-web-azure-functions
    metadata:
      queueName: dataimport-transformload-queue
      queueLength: "1"                                                      #  <--- Amount of load a pod can handle